# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Jul 15 11:48:38 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 768)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 881, 731))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtGui.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.stackedWidget = QtGui.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 431, 721))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 431, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.basic = QtGui.QWidget()
        self.basic.setEnabled(True)
        self.basic.setObjectName("basic")
        self.layoutWidget1 = QtGui.QWidget(self.basic)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 1, 441, 661))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 140))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 25, 421, 98))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget2)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setStyleSheet("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_5.addWidget(self.checkBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 20, 421, 64))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 21, 421, 98))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_11.addWidget(self.lineEdit_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtGui.QLabel(self.layoutWidget4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_12.addWidget(self.lineEdit_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtGui.QLabel(self.layoutWidget4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_13.addWidget(self.lineEdit_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 20, 421, 64))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtGui.QLabel(self.layoutWidget5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.comboBox = QtGui.QComboBox(self.layoutWidget5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtGui.QLabel(self.layoutWidget5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBox_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_8 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget_8.setGeometry(QtCore.QRect(0, 20, 421, 64))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtGui.QLabel(self.layoutWidget_8)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_16.addWidget(self.lineEdit_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtGui.QLabel(self.layoutWidget_8)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget_8)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_17.addWidget(self.lineEdit_14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.verticalLayout_11.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.basic, "")
        self.advanced = QtGui.QWidget()
        self.advanced.setObjectName("advanced")
        self.widget1 = QtGui.QWidget(self.advanced)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 431, 671))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_9 = QtGui.QGroupBox(self.widget1)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.verticalLayout_7.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.widget1)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 90))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_8.addWidget(self.lineEdit_7)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 50, 421, 28))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtGui.QLabel(self.layoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_9.addWidget(self.lineEdit_8)
        self.verticalLayout_7.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(self.widget1)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtGui.QLabel(self.layoutWidget_7)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget_7)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_19.addWidget(self.lineEdit_16)
        self.layoutWidget_9 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget_9.setGeometry(QtCore.QRect(0, 50, 421, 30))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtGui.QLabel(self.layoutWidget_9)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget_9)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_20.addWidget(self.lineEdit_17)
        self.layoutWidget_10 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 80, 421, 28))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtGui.QLabel(self.layoutWidget_10)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.lineEdit_18 = QtGui.QLineEdit(self.layoutWidget_10)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_21.addWidget(self.lineEdit_18)
        self.layoutWidget_11 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget_11.setGeometry(QtCore.QRect(0, 110, 421, 31))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtGui.QLabel(self.layoutWidget_11)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.lineEdit_19 = QtGui.QLineEdit(self.layoutWidget_11)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_22.addWidget(self.lineEdit_19)
        self.verticalLayout_7.addWidget(self.groupBox_11)
        self.groupBox_12 = QtGui.QGroupBox(self.widget1)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 170))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 190))
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget_12 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 30, 421, 28))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtGui.QLabel(self.layoutWidget_12)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        self.lineEdit_20 = QtGui.QLineEdit(self.layoutWidget_12)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_23.addWidget(self.lineEdit_20)
        self.layoutWidget_13 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget_13.setGeometry(QtCore.QRect(0, 60, 421, 28))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_23 = QtGui.QLabel(self.layoutWidget_13)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        self.lineEdit_21 = QtGui.QLineEdit(self.layoutWidget_13)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_24.addWidget(self.lineEdit_21)
        self.layoutWidget_14 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget_14.setGeometry(QtCore.QRect(0, 90, 421, 28))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtGui.QLabel(self.layoutWidget_14)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.lineEdit_22 = QtGui.QLineEdit(self.layoutWidget_14)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_25.addWidget(self.lineEdit_22)
        self.layoutWidget_15 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget_15.setGeometry(QtCore.QRect(0, 120, 421, 28))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtGui.QLabel(self.layoutWidget_15)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        self.lineEdit_23 = QtGui.QLineEdit(self.layoutWidget_15)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_26.addWidget(self.lineEdit_23)
        self.layoutWidget_16 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget_16.setGeometry(QtCore.QRect(0, 150, 421, 28))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtGui.QLabel(self.layoutWidget_16)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        self.lineEdit_25 = QtGui.QLineEdit(self.layoutWidget_16)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_28.addWidget(self.lineEdit_25)
        self.verticalLayout_7.addWidget(self.groupBox_12)
        self.groupBox_13 = QtGui.QGroupBox(self.widget1)
        self.groupBox_13.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget_17 = QtGui.QWidget(self.groupBox_13)
        self.layoutWidget_17.setGeometry(QtCore.QRect(0, 30, 421, 28))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_28 = QtGui.QLabel(self.layoutWidget_17)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_29.addWidget(self.label_28)
        self.lineEdit_26 = QtGui.QLineEdit(self.layoutWidget_17)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_29.addWidget(self.lineEdit_26)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_13)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 60, 421, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_7.addWidget(self.groupBox_13)
        self.tabWidget.addTab(self.advanced, "")
        self.plugins = QtGui.QWidget()
        self.plugins.setObjectName("plugins")
        self.groupBox_14 = QtGui.QGroupBox(self.plugins)
        self.groupBox_14.setGeometry(QtCore.QRect(0, 0, 421, 111))
        self.groupBox_14.setObjectName("groupBox_14")
        self.listWidget = QtGui.QListWidget(self.groupBox_14)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 401, 81))
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.pushButton = QtGui.QPushButton(self.plugins)
        self.pushButton.setGeometry(QtCore.QRect(150, 110, 86, 27))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_15 = QtGui.QGroupBox(self.plugins)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 150, 411, 281))
        self.groupBox_15.setObjectName("groupBox_15")
        self.tabWidget.addTab(self.plugins, "")
        self.start_end_gcode = QtGui.QWidget()
        self.start_end_gcode.setObjectName("start_end_gcode")
        self.listWidget_2 = QtGui.QListWidget(self.start_end_gcode)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 431, 91))
        self.listWidget_2.setObjectName("listWidget_2")
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        self.textEdit = QtGui.QTextEdit(self.start_end_gcode)
        self.textEdit.setGeometry(QtCore.QRect(0, 100, 431, 561))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.start_end_gcode, "")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget6 = QtGui.QWidget(self.page_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 201, 361))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget6)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget7 = QtGui.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(4, 20, 171, 77))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtGui.QRadioButton(self.layoutWidget7)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.layoutWidget7)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.layoutWidget7)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget6)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget8 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 131, 104))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_4 = QtGui.QRadioButton(self.layoutWidget8)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.layoutWidget8)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.label = QtGui.QLabel(self.layoutWidget8)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget6)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(0, 20, 181, 21))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_3.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 24))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        self.menuMachine = QtGui.QMenu(self.menubar)
        self.menuMachine.setObjectName("menuMachine")
        self.menuExpert = QtGui.QMenu(self.menubar)
        self.menuExpert.setObjectName("menuExpert")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_model_file_tCTRL_L = QtGui.QAction(MainWindow)
        self.actionLoad_model_file_tCTRL_L.setObjectName("actionLoad_model_file_tCTRL_L")
        self.actionSave_model = QtGui.QAction(MainWindow)
        self.actionSave_model.setObjectName("actionSave_model")
        self.actionReload_platform = QtGui.QAction(MainWindow)
        self.actionReload_platform.setObjectName("actionReload_platform")
        self.actionReload_platform_2 = QtGui.QAction(MainWindow)
        self.actionReload_platform_2.setObjectName("actionReload_platform_2")
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_GCode = QtGui.QAction(MainWindow)
        self.actionSave_GCode.setObjectName("actionSave_GCode")
        self.actionShow_slice_engine_log = QtGui.QAction(MainWindow)
        self.actionShow_slice_engine_log.setObjectName("actionShow_slice_engine_log")
        self.actionOpen_Profile = QtGui.QAction(MainWindow)
        self.actionOpen_Profile.setObjectName("actionOpen_Profile")
        self.actionSave_Profile = QtGui.QAction(MainWindow)
        self.actionSave_Profile.setObjectName("actionSave_Profile")
        self.actionLoad_Profile_from_GCode = QtGui.QAction(MainWindow)
        self.actionLoad_Profile_from_GCode.setObjectName("actionLoad_Profile_from_GCode")
        self.actionReset_Profile_to_default = QtGui.QAction(MainWindow)
        self.actionReset_Profile_to_default.setObjectName("actionReset_Profile_to_default")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMachine_settings = QtGui.QAction(MainWindow)
        self.actionMachine_settings.setObjectName("actionMachine_settings")
        self.actionRecent_Model_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Model_Files.setObjectName("actionRecent_Model_Files")
        self.actionRecent_Profile_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Profile_Files.setObjectName("actionRecent_Profile_Files")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPID_Debugger = QtGui.QAction(MainWindow)
        self.actionPID_Debugger.setObjectName("actionPID_Debugger")
        self.actionCopy_profile_to_clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_profile_to_clipboard.setObjectName("actionCopy_profile_to_clipboard")
        self.actionPrint_all_at_once = QtGui.QAction(MainWindow)
        self.actionPrint_all_at_once.setObjectName("actionPrint_all_at_once")
        self.actionPrint_one_at_a_time = QtGui.QAction(MainWindow)
        self.actionPrint_one_at_a_time.setObjectName("actionPrint_one_at_a_time")
        self.actionMachine_settings_2 = QtGui.QAction(MainWindow)
        self.actionMachine_settings_2.setObjectName("actionMachine_settings_2")
        self.actionInstall_custom_firmware = QtGui.QAction(MainWindow)
        self.actionInstall_custom_firmware.setObjectName("actionInstall_custom_firmware")
        self.actionSwitch_to_quickprint = QtGui.QAction(MainWindow)
        self.actionSwitch_to_quickprint.setObjectName("actionSwitch_to_quickprint")
        self.actionSwitch_to_expert_mode = QtGui.QAction(MainWindow)
        self.actionSwitch_to_expert_mode.setObjectName("actionSwitch_to_expert_mode")
        self.actionOpen_expert_settings = QtGui.QAction(MainWindow)
        self.actionOpen_expert_settings.setObjectName("actionOpen_expert_settings")
        self.actionRun_first_run_wizard = QtGui.QAction(MainWindow)
        self.actionRun_first_run_wizard.setObjectName("actionRun_first_run_wizard")
        self.actionRun_bed_leveling_wizard = QtGui.QAction(MainWindow)
        self.actionRun_bed_leveling_wizard.setObjectName("actionRun_bed_leveling_wizard")
        self.actionRun_head_offset_wizard = QtGui.QAction(MainWindow)
        self.actionRun_head_offset_wizard.setObjectName("actionRun_head_offset_wizard")
        self.actionOnline_documentation = QtGui.QAction(MainWindow)
        self.actionOnline_documentation.setObjectName("actionOnline_documentation")
        self.actionReport_a_problem = QtGui.QAction(MainWindow)
        self.actionReport_a_problem.setObjectName("actionReport_a_problem")
        self.actionCheck_for_update = QtGui.QAction(MainWindow)
        self.actionCheck_for_update.setObjectName("actionCheck_for_update")
        self.menu_File.addAction(self.actionLoad_model_file_tCTRL_L)
        self.menu_File.addAction(self.actionSave_model)
        self.menu_File.addAction(self.actionReload_platform)
        self.menu_File.addAction(self.actionReload_platform_2)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPrint)
        self.menu_File.addAction(self.actionSave_GCode)
        self.menu_File.addAction(self.actionShow_slice_engine_log)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen_Profile)
        self.menu_File.addAction(self.actionSave_Profile)
        self.menu_File.addAction(self.actionLoad_Profile_from_GCode)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionReset_Profile_to_default)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPreferences)
        self.menu_File.addAction(self.actionMachine_settings)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionRecent_Model_Files)
        self.menu_File.addAction(self.actionRecent_Profile_Files)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Tools.addAction(self.actionPID_Debugger)
        self.menu_Tools.addAction(self.actionCopy_profile_to_clipboard)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionPrint_all_at_once)
        self.menu_Tools.addAction(self.actionPrint_one_at_a_time)
        self.menuMachine.addAction(self.actionMachine_settings_2)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionInstall_custom_firmware)
        self.menuExpert.addAction(self.actionSwitch_to_quickprint)
        self.menuExpert.addAction(self.actionSwitch_to_expert_mode)
        self.menuExpert.addSeparator()
        self.menuExpert.addAction(self.actionOpen_expert_settings)
        self.menuExpert.addSeparator()
        self.menuExpert.addAction(self.actionRun_first_run_wizard)
        self.menuExpert.addAction(self.actionRun_bed_leveling_wizard)
        self.menuExpert.addAction(self.actionRun_head_offset_wizard)
        self.menuHelp.addAction(self.actionOnline_documentation)
        self.menuHelp.addAction(self.actionReport_a_problem)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuMachine.menuAction())
        self.menubar.addAction(self.menuExpert.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.basic.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Layer height (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Shell thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Enable retraction", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Bottom/Top thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Fill density (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Speed and Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Print speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Printing temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Bed temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Support type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Touching buildplate", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Everywhere", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Platform adhesion type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Brim", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "Raft", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Filament", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Diameter (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Flow (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic), QtGui.QApplication.translate("MainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Nozzle size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Retraction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Distance (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Initial layer thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Initial layer line with (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Cut off object bottom (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Dual extursion overlap (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Travel speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Bottom layer speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Infill speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Outer shell speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Inner shell speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Cool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Minimal layer time (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("MainWindow", "Enable cooling fan", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced), QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("MainWindow", "Tweak At Z 3.1.2", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("MainWindow", "Pause at height", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", "Enabled plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plugins), QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        self.listWidget_2.item(0).setText(QtGui.QApplication.translate("MainWindow", "start.gcode", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(1).setText(QtGui.QApplication.translate("MainWindow", "end.gcode", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.start_end_gcode), QtGui.QApplication.translate("MainWindow", "Start/End-GCode", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Select a quickprint profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "High quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Normal quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Fast low quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "PLA", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "ABS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Diameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Print support structure", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMachine.setTitle(QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExpert.setTitle(QtGui.QApplication.translate("MainWindow", "Expert", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_model_file_tCTRL_L.setText(QtGui.QApplication.translate("MainWindow", "Load model file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_model.setText(QtGui.QApplication.translate("MainWindow", "Save model...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_platform.setText(QtGui.QApplication.translate("MainWindow", "Reload platform", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_platform_2.setText(QtGui.QApplication.translate("MainWindow", "Clear platform", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_GCode.setText(QtGui.QApplication.translate("MainWindow", "Save GCode...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_slice_engine_log.setText(QtGui.QApplication.translate("MainWindow", "Show slice engine log...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Profile.setText(QtGui.QApplication.translate("MainWindow", "Open Profile...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Profile.setText(QtGui.QApplication.translate("MainWindow", "Save Profile...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Profile_from_GCode.setText(QtGui.QApplication.translate("MainWindow", "Load Profile from GCode...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Profile_to_default.setText(QtGui.QApplication.translate("MainWindow", "Reset Profile to default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMachine_settings.setText(QtGui.QApplication.translate("MainWindow", "Machine settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Model_Files.setText(QtGui.QApplication.translate("MainWindow", "Recent Model Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Profile_Files.setText(QtGui.QApplication.translate("MainWindow", "Recent Profile Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPID_Debugger.setText(QtGui.QApplication.translate("MainWindow", "PID Debugger...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_profile_to_clipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy profile to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_all_at_once.setText(QtGui.QApplication.translate("MainWindow", "Print all at once", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_one_at_a_time.setText(QtGui.QApplication.translate("MainWindow", "Print one at a time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMachine_settings_2.setText(QtGui.QApplication.translate("MainWindow", "Machine settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInstall_custom_firmware.setText(QtGui.QApplication.translate("MainWindow", "Install custom firmware...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_to_quickprint.setText(QtGui.QApplication.translate("MainWindow", "Switch to quickprint...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_to_expert_mode.setText(QtGui.QApplication.translate("MainWindow", "Switch to full settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_expert_settings.setText(QtGui.QApplication.translate("MainWindow", "Open expert settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_first_run_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run first run wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_bed_leveling_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run bed leveling wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_head_offset_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run head offset wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_documentation.setText(QtGui.QApplication.translate("MainWindow", "Online documentation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_problem.setText(QtGui.QApplication.translate("MainWindow", "Report a problem...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_update.setText(QtGui.QApplication.translate("MainWindow", "Check for update...", None, QtGui.QApplication.UnicodeUTF8))

