# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created: Mon Jul 28 13:59:58 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 1180, 654))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -2, 1100, 849))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 851))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_widget = QtGui.QWidget(self.layoutWidget)
        self.left_widget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_widget.sizePolicy().hasHeightForWidth())
        self.left_widget.setSizePolicy(sizePolicy)
        self.left_widget.setObjectName("left_widget")
        self.slice_modes = QtGui.QStackedWidget(self.left_widget)
        self.slice_modes.setGeometry(QtCore.QRect(0, 0, 600, 849))
        self.slice_modes.setObjectName("slice_modes")
        self.normal = QtGui.QWidget()
        self.normal.setObjectName("normal")
        self.tabWidget = QtGui.QTabWidget(self.normal)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 481, 921))
        self.tabWidget.setObjectName("tabWidget")
        self.basic = QtGui.QWidget()
        self.basic.setEnabled(True)
        self.basic.setObjectName("basic")
        self.layoutWidget1 = QtGui.QWidget(self.basic)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 2, 471, 881))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.quality_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.quality_groupbox.setMinimumSize(QtCore.QSize(0, 125))
        self.quality_groupbox.setMaximumSize(QtCore.QSize(16777215, 125))
        self.quality_groupbox.setObjectName("quality_groupbox")
        self.layoutWidget2 = QtGui.QWidget(self.quality_groupbox)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 25, 421, 98))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layer_height_label = QtGui.QLabel(self.layoutWidget2)
        self.layer_height_label.setObjectName("layer_height_label")
        self.horizontalLayout.addWidget(self.layer_height_label)
        self.layer_height = QtGui.QLineEdit(self.layoutWidget2)
        self.layer_height.setObjectName("layer_height")
        self.horizontalLayout.addWidget(self.layer_height)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wall_thickness_label = QtGui.QLabel(self.layoutWidget2)
        self.wall_thickness_label.setObjectName("wall_thickness_label")
        self.horizontalLayout_4.addWidget(self.wall_thickness_label)
        self.wall_thickness = QtGui.QLineEdit(self.layoutWidget2)
        self.wall_thickness.setObjectName("wall_thickness")
        self.horizontalLayout_4.addWidget(self.wall_thickness)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.retraction_enable = QtGui.QCheckBox(self.layoutWidget2)
        self.retraction_enable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.retraction_enable.setStyleSheet("")
        self.retraction_enable.setObjectName("retraction_enable")
        self.horizontalLayout_5.addWidget(self.retraction_enable)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addWidget(self.quality_groupbox)
        self.fill_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.fill_groupbox.setMaximumSize(QtCore.QSize(16777215, 90))
        self.fill_groupbox.setObjectName("fill_groupbox")
        self.layoutWidget3 = QtGui.QWidget(self.fill_groupbox)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 20, 421, 80))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.solid_layer_thickness_label = QtGui.QLabel(self.layoutWidget3)
        self.solid_layer_thickness_label.setObjectName("solid_layer_thickness_label")
        self.horizontalLayout_2.addWidget(self.solid_layer_thickness_label)
        self.solid_layer_thickness = QtGui.QLineEdit(self.layoutWidget3)
        self.solid_layer_thickness.setObjectName("solid_layer_thickness")
        self.horizontalLayout_2.addWidget(self.solid_layer_thickness)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.fill_density_label = QtGui.QLabel(self.layoutWidget3)
        self.fill_density_label.setObjectName("fill_density_label")
        self.horizontalLayout_6.addWidget(self.fill_density_label)
        self.fill_density = QtGui.QLineEdit(self.layoutWidget3)
        self.fill_density.setObjectName("fill_density")
        self.horizontalLayout_6.addWidget(self.fill_density)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.fill_groupbox)
        self.speed_temperature_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.speed_temperature_groupbox.setMinimumSize(QtCore.QSize(0, 230))
        self.speed_temperature_groupbox.setMaximumSize(QtCore.QSize(16777215, 230))
        self.speed_temperature_groupbox.setObjectName("speed_temperature_groupbox")
        self.layoutWidget4 = QtGui.QWidget(self.speed_temperature_groupbox)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 23, 421, 200))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.print_speed_label = QtGui.QLabel(self.layoutWidget4)
        self.print_speed_label.setObjectName("print_speed_label")
        self.horizontalLayout_11.addWidget(self.print_speed_label)
        self.print_speed = QtGui.QLineEdit(self.layoutWidget4)
        self.print_speed.setObjectName("print_speed")
        self.horizontalLayout_11.addWidget(self.print_speed)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.print_temperature_label = QtGui.QLabel(self.layoutWidget4)
        self.print_temperature_label.setObjectName("print_temperature_label")
        self.horizontalLayout_12.addWidget(self.print_temperature_label)
        self.print_temperature = QtGui.QLineEdit(self.layoutWidget4)
        self.print_temperature.setObjectName("print_temperature")
        self.horizontalLayout_12.addWidget(self.print_temperature)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.print_temperature2_label = QtGui.QLabel(self.layoutWidget4)
        self.print_temperature2_label.setObjectName("print_temperature2_label")
        self.horizontalLayout_13.addWidget(self.print_temperature2_label)
        self.print_temperature2 = QtGui.QLineEdit(self.layoutWidget4)
        self.print_temperature2.setObjectName("print_temperature2")
        self.horizontalLayout_13.addWidget(self.print_temperature2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.print_temperature3_label = QtGui.QLabel(self.layoutWidget4)
        self.print_temperature3_label.setObjectName("print_temperature3_label")
        self.horizontalLayout_32.addWidget(self.print_temperature3_label)
        self.print_temperature3 = QtGui.QLineEdit(self.layoutWidget4)
        self.print_temperature3.setObjectName("print_temperature3")
        self.horizontalLayout_32.addWidget(self.print_temperature3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.print_temperature4_label = QtGui.QLabel(self.layoutWidget4)
        self.print_temperature4_label.setObjectName("print_temperature4_label")
        self.horizontalLayout_33.addWidget(self.print_temperature4_label)
        self.print_temperature4 = QtGui.QLineEdit(self.layoutWidget4)
        self.print_temperature4.setObjectName("print_temperature4")
        self.horizontalLayout_33.addWidget(self.print_temperature4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.print_bed_temperature_label = QtGui.QLabel(self.layoutWidget4)
        self.print_bed_temperature_label.setObjectName("print_bed_temperature_label")
        self.horizontalLayout_31.addWidget(self.print_bed_temperature_label)
        self.print_bed_temperature = QtGui.QLineEdit(self.layoutWidget4)
        self.print_bed_temperature.setObjectName("print_bed_temperature")
        self.horizontalLayout_31.addWidget(self.print_bed_temperature)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.verticalLayout_11.addWidget(self.speed_temperature_groupbox)
        self.support_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.support_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.support_groupbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.support_groupbox.setObjectName("support_groupbox")
        self.layoutWidget5 = QtGui.QWidget(self.support_groupbox)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 21, 421, 98))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.support_label = QtGui.QLabel(self.layoutWidget5)
        self.support_label.setObjectName("support_label")
        self.horizontalLayout_14.addWidget(self.support_label)
        self.support = QtGui.QComboBox(self.layoutWidget5)
        self.support.setObjectName("support")
        self.horizontalLayout_14.addWidget(self.support)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.platform_adhesion_label = QtGui.QLabel(self.layoutWidget5)
        self.platform_adhesion_label.setObjectName("platform_adhesion_label")
        self.horizontalLayout_15.addWidget(self.platform_adhesion_label)
        self.platform_adhesion = QtGui.QComboBox(self.layoutWidget5)
        self.platform_adhesion.setObjectName("platform_adhesion")
        self.horizontalLayout_15.addWidget(self.platform_adhesion)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.support_dual_extrusion_label = QtGui.QLabel(self.layoutWidget5)
        self.support_dual_extrusion_label.setObjectName("support_dual_extrusion_label")
        self.horizontalLayout_34.addWidget(self.support_dual_extrusion_label)
        self.support_dual_extrusion = QtGui.QComboBox(self.layoutWidget5)
        self.support_dual_extrusion.setObjectName("support_dual_extrusion")
        self.horizontalLayout_34.addWidget(self.support_dual_extrusion)
        self.verticalLayout_8.addLayout(self.horizontalLayout_34)
        self.verticalLayout_11.addWidget(self.support_groupbox)
        self.dual_extursion_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.dual_extursion_groupbox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.dual_extursion_groupbox.setObjectName("dual_extursion_groupbox")
        self.layoutWidget6 = QtGui.QWidget(self.dual_extursion_groupbox)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 20, 421, 50))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.wipe_tower = QtGui.QCheckBox(self.layoutWidget6)
        self.wipe_tower.setObjectName("wipe_tower")
        self.verticalLayout_9.addWidget(self.wipe_tower)
        self.ooze_shield = QtGui.QCheckBox(self.layoutWidget6)
        self.ooze_shield.setObjectName("ooze_shield")
        self.verticalLayout_9.addWidget(self.ooze_shield)
        self.verticalLayout_11.addWidget(self.dual_extursion_groupbox)
        self.filament_groupbox = QtGui.QGroupBox(self.layoutWidget1)
        self.filament_groupbox.setObjectName("filament_groupbox")
        self.layoutWidget7 = QtGui.QWidget(self.filament_groupbox)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 21, 421, 166))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.filament_diameter_label = QtGui.QLabel(self.layoutWidget7)
        self.filament_diameter_label.setObjectName("filament_diameter_label")
        self.horizontalLayout_16.addWidget(self.filament_diameter_label)
        self.filament_diameter = QtGui.QLineEdit(self.layoutWidget7)
        self.filament_diameter.setObjectName("filament_diameter")
        self.horizontalLayout_16.addWidget(self.filament_diameter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.filament_diameter2_label = QtGui.QLabel(self.layoutWidget7)
        self.filament_diameter2_label.setObjectName("filament_diameter2_label")
        self.horizontalLayout_35.addWidget(self.filament_diameter2_label)
        self.filament_diameter2 = QtGui.QLineEdit(self.layoutWidget7)
        self.filament_diameter2.setObjectName("filament_diameter2")
        self.horizontalLayout_35.addWidget(self.filament_diameter2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.filament_diameter3_label = QtGui.QLabel(self.layoutWidget7)
        self.filament_diameter3_label.setObjectName("filament_diameter3_label")
        self.horizontalLayout_36.addWidget(self.filament_diameter3_label)
        self.filament_diameter3 = QtGui.QLineEdit(self.layoutWidget7)
        self.filament_diameter3.setObjectName("filament_diameter3")
        self.horizontalLayout_36.addWidget(self.filament_diameter3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.filament_diameter4_label = QtGui.QLabel(self.layoutWidget7)
        self.filament_diameter4_label.setObjectName("filament_diameter4_label")
        self.horizontalLayout_37.addWidget(self.filament_diameter4_label)
        self.filament_diameter4 = QtGui.QLineEdit(self.layoutWidget7)
        self.filament_diameter4.setObjectName("filament_diameter4")
        self.horizontalLayout_37.addWidget(self.filament_diameter4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.filament_flow_label = QtGui.QLabel(self.layoutWidget7)
        self.filament_flow_label.setObjectName("filament_flow_label")
        self.horizontalLayout_17.addWidget(self.filament_flow_label)
        self.filament_flow = QtGui.QLineEdit(self.layoutWidget7)
        self.filament_flow.setObjectName("filament_flow")
        self.horizontalLayout_17.addWidget(self.filament_flow)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.verticalLayout_11.addWidget(self.filament_groupbox)
        self.tabWidget.addTab(self.basic, "")
        self.advanced = QtGui.QWidget()
        self.advanced.setObjectName("advanced")
        self.layoutWidget8 = QtGui.QWidget(self.advanced)
        self.layoutWidget8.setGeometry(QtCore.QRect(0, 1, 461, 881))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.machine_groupbox = QtGui.QGroupBox(self.layoutWidget8)
        self.machine_groupbox.setMinimumSize(QtCore.QSize(0, 50))
        self.machine_groupbox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.machine_groupbox.setObjectName("machine_groupbox")
        self.layoutWidget_2 = QtGui.QWidget(self.machine_groupbox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nozzle_size_label = QtGui.QLabel(self.layoutWidget_2)
        self.nozzle_size_label.setObjectName("nozzle_size_label")
        self.horizontalLayout_7.addWidget(self.nozzle_size_label)
        self.nozzle_size = QtGui.QLineEdit(self.layoutWidget_2)
        self.nozzle_size.setObjectName("nozzle_size")
        self.horizontalLayout_7.addWidget(self.nozzle_size)
        self.verticalLayout_7.addWidget(self.machine_groupbox)
        self.retraction_groupbox = QtGui.QGroupBox(self.layoutWidget8)
        self.retraction_groupbox.setMinimumSize(QtCore.QSize(0, 120))
        self.retraction_groupbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.retraction_groupbox.setObjectName("retraction_groupbox")
        self.layoutWidget_3 = QtGui.QWidget(self.retraction_groupbox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.retraction_speed_label = QtGui.QLabel(self.layoutWidget_3)
        self.retraction_speed_label.setObjectName("retraction_speed_label")
        self.horizontalLayout_8.addWidget(self.retraction_speed_label)
        self.retraction_speed = QtGui.QLineEdit(self.layoutWidget_3)
        self.retraction_speed.setObjectName("retraction_speed")
        self.horizontalLayout_8.addWidget(self.retraction_speed)
        self.layoutWidget_4 = QtGui.QWidget(self.retraction_groupbox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 50, 421, 28))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.retraction_amount_label = QtGui.QLabel(self.layoutWidget_4)
        self.retraction_amount_label.setObjectName("retraction_amount_label")
        self.horizontalLayout_9.addWidget(self.retraction_amount_label)
        self.retraction_amount = QtGui.QLineEdit(self.layoutWidget_4)
        self.retraction_amount.setObjectName("retraction_amount")
        self.horizontalLayout_9.addWidget(self.retraction_amount)
        self.layoutWidget_24 = QtGui.QWidget(self.retraction_groupbox)
        self.layoutWidget_24.setGeometry(QtCore.QRect(0, 80, 421, 28))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.retraction_dual_amount_label = QtGui.QLabel(self.layoutWidget_24)
        self.retraction_dual_amount_label.setObjectName("retraction_dual_amount_label")
        self.horizontalLayout_38.addWidget(self.retraction_dual_amount_label)
        self.retraction_dual_amount = QtGui.QLineEdit(self.layoutWidget_24)
        self.retraction_dual_amount.setObjectName("retraction_dual_amount")
        self.horizontalLayout_38.addWidget(self.retraction_dual_amount)
        self.verticalLayout_7.addWidget(self.retraction_groupbox)
        self.quality_groupbox_advanced = QtGui.QGroupBox(self.layoutWidget8)
        self.quality_groupbox_advanced.setMinimumSize(QtCore.QSize(0, 150))
        self.quality_groupbox_advanced.setMaximumSize(QtCore.QSize(16777215, 150))
        self.quality_groupbox_advanced.setObjectName("quality_groupbox_advanced")
        self.layoutWidget_7 = QtGui.QWidget(self.quality_groupbox_advanced)
        self.layoutWidget_7.setGeometry(QtCore.QRect(0, 20, 421, 28))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.bottom_thickness_label = QtGui.QLabel(self.layoutWidget_7)
        self.bottom_thickness_label.setObjectName("bottom_thickness_label")
        self.horizontalLayout_19.addWidget(self.bottom_thickness_label)
        self.bottom_thickness = QtGui.QLineEdit(self.layoutWidget_7)
        self.bottom_thickness.setObjectName("bottom_thickness")
        self.horizontalLayout_19.addWidget(self.bottom_thickness)
        self.layoutWidget_9 = QtGui.QWidget(self.quality_groupbox_advanced)
        self.layoutWidget_9.setGeometry(QtCore.QRect(0, 50, 421, 30))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.layer0_width_factor_label = QtGui.QLabel(self.layoutWidget_9)
        self.layer0_width_factor_label.setObjectName("layer0_width_factor_label")
        self.horizontalLayout_20.addWidget(self.layer0_width_factor_label)
        self.layer0_width_factor = QtGui.QLineEdit(self.layoutWidget_9)
        self.layer0_width_factor.setObjectName("layer0_width_factor")
        self.horizontalLayout_20.addWidget(self.layer0_width_factor)
        self.layoutWidget_10 = QtGui.QWidget(self.quality_groupbox_advanced)
        self.layoutWidget_10.setGeometry(QtCore.QRect(0, 80, 421, 28))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.object_sink_label = QtGui.QLabel(self.layoutWidget_10)
        self.object_sink_label.setObjectName("object_sink_label")
        self.horizontalLayout_21.addWidget(self.object_sink_label)
        self.object_sink = QtGui.QLineEdit(self.layoutWidget_10)
        self.object_sink.setObjectName("object_sink")
        self.horizontalLayout_21.addWidget(self.object_sink)
        self.layoutWidget_11 = QtGui.QWidget(self.quality_groupbox_advanced)
        self.layoutWidget_11.setGeometry(QtCore.QRect(0, 110, 421, 31))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.overlap_dual_label = QtGui.QLabel(self.layoutWidget_11)
        self.overlap_dual_label.setObjectName("overlap_dual_label")
        self.horizontalLayout_22.addWidget(self.overlap_dual_label)
        self.overlap_dual = QtGui.QLineEdit(self.layoutWidget_11)
        self.overlap_dual.setObjectName("overlap_dual")
        self.horizontalLayout_22.addWidget(self.overlap_dual)
        self.verticalLayout_7.addWidget(self.quality_groupbox_advanced)
        self.speed_groupbox = QtGui.QGroupBox(self.layoutWidget8)
        self.speed_groupbox.setMinimumSize(QtCore.QSize(0, 170))
        self.speed_groupbox.setMaximumSize(QtCore.QSize(16777215, 190))
        self.speed_groupbox.setObjectName("speed_groupbox")
        self.layoutWidget_12 = QtGui.QWidget(self.speed_groupbox)
        self.layoutWidget_12.setGeometry(QtCore.QRect(0, 30, 421, 28))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.travel_speed_label = QtGui.QLabel(self.layoutWidget_12)
        self.travel_speed_label.setObjectName("travel_speed_label")
        self.horizontalLayout_23.addWidget(self.travel_speed_label)
        self.travel_speed = QtGui.QLineEdit(self.layoutWidget_12)
        self.travel_speed.setObjectName("travel_speed")
        self.horizontalLayout_23.addWidget(self.travel_speed)
        self.layoutWidget_13 = QtGui.QWidget(self.speed_groupbox)
        self.layoutWidget_13.setGeometry(QtCore.QRect(0, 60, 421, 28))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bottom_layer_speed_label = QtGui.QLabel(self.layoutWidget_13)
        self.bottom_layer_speed_label.setObjectName("bottom_layer_speed_label")
        self.horizontalLayout_24.addWidget(self.bottom_layer_speed_label)
        self.bottom_layer_speed = QtGui.QLineEdit(self.layoutWidget_13)
        self.bottom_layer_speed.setObjectName("bottom_layer_speed")
        self.horizontalLayout_24.addWidget(self.bottom_layer_speed)
        self.layoutWidget_14 = QtGui.QWidget(self.speed_groupbox)
        self.layoutWidget_14.setGeometry(QtCore.QRect(0, 90, 421, 28))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.infill_speed_label = QtGui.QLabel(self.layoutWidget_14)
        self.infill_speed_label.setObjectName("infill_speed_label")
        self.horizontalLayout_25.addWidget(self.infill_speed_label)
        self.infill_speed = QtGui.QLineEdit(self.layoutWidget_14)
        self.infill_speed.setObjectName("infill_speed")
        self.horizontalLayout_25.addWidget(self.infill_speed)
        self.layoutWidget_15 = QtGui.QWidget(self.speed_groupbox)
        self.layoutWidget_15.setGeometry(QtCore.QRect(0, 120, 421, 28))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.inset0_speed_label = QtGui.QLabel(self.layoutWidget_15)
        self.inset0_speed_label.setObjectName("inset0_speed_label")
        self.horizontalLayout_26.addWidget(self.inset0_speed_label)
        self.inset0_speed = QtGui.QLineEdit(self.layoutWidget_15)
        self.inset0_speed.setObjectName("inset0_speed")
        self.horizontalLayout_26.addWidget(self.inset0_speed)
        self.layoutWidget_16 = QtGui.QWidget(self.speed_groupbox)
        self.layoutWidget_16.setGeometry(QtCore.QRect(0, 150, 421, 28))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.insetx_speed_label = QtGui.QLabel(self.layoutWidget_16)
        self.insetx_speed_label.setObjectName("insetx_speed_label")
        self.horizontalLayout_28.addWidget(self.insetx_speed_label)
        self.insetx_speed = QtGui.QLineEdit(self.layoutWidget_16)
        self.insetx_speed.setObjectName("insetx_speed")
        self.horizontalLayout_28.addWidget(self.insetx_speed)
        self.verticalLayout_7.addWidget(self.speed_groupbox)
        self.cool_groupbox = QtGui.QGroupBox(self.layoutWidget8)
        self.cool_groupbox.setMinimumSize(QtCore.QSize(0, 80))
        self.cool_groupbox.setObjectName("cool_groupbox")
        self.layoutWidget_17 = QtGui.QWidget(self.cool_groupbox)
        self.layoutWidget_17.setGeometry(QtCore.QRect(0, 30, 421, 28))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.cool_min_layer_time_label = QtGui.QLabel(self.layoutWidget_17)
        self.cool_min_layer_time_label.setObjectName("cool_min_layer_time_label")
        self.horizontalLayout_29.addWidget(self.cool_min_layer_time_label)
        self.cool_min_layer_time = QtGui.QLineEdit(self.layoutWidget_17)
        self.cool_min_layer_time.setObjectName("cool_min_layer_time")
        self.horizontalLayout_29.addWidget(self.cool_min_layer_time)
        self.fan_enabled = QtGui.QCheckBox(self.cool_groupbox)
        self.fan_enabled.setGeometry(QtCore.QRect(0, 60, 421, 21))
        self.fan_enabled.setObjectName("fan_enabled")
        self.verticalLayout_7.addWidget(self.cool_groupbox)
        self.tabWidget.addTab(self.advanced, "")
        self.plugins = QtGui.QWidget()
        self.plugins.setObjectName("plugins")
        self.plugins_groupbox = QtGui.QGroupBox(self.plugins)
        self.plugins_groupbox.setGeometry(QtCore.QRect(0, 0, 421, 111))
        self.plugins_groupbox.setObjectName("plugins_groupbox")
        self.plugin_config = QtGui.QListWidget(self.plugins_groupbox)
        self.plugin_config.setGeometry(QtCore.QRect(10, 20, 401, 81))
        self.plugin_config.setObjectName("plugin_config")
        QtGui.QListWidgetItem(self.plugin_config)
        QtGui.QListWidgetItem(self.plugin_config)
        self.pushButton = QtGui.QPushButton(self.plugins)
        self.pushButton.setGeometry(QtCore.QRect(150, 110, 86, 27))
        self.pushButton.setObjectName("pushButton")
        self.enabled_plugins_groupbox = QtGui.QGroupBox(self.plugins)
        self.enabled_plugins_groupbox.setGeometry(QtCore.QRect(0, 150, 411, 281))
        self.enabled_plugins_groupbox.setObjectName("enabled_plugins_groupbox")
        self.tabWidget.addTab(self.plugins, "")
        self.start_end_gcode = QtGui.QWidget()
        self.start_end_gcode.setObjectName("start_end_gcode")
        self.listWidget_2 = QtGui.QListWidget(self.start_end_gcode)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 431, 91))
        self.listWidget_2.setObjectName("listWidget_2")
        QtGui.QListWidgetItem(self.listWidget_2)
        QtGui.QListWidgetItem(self.listWidget_2)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.start_end_gcode)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 100, 431, 771))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.startgcode = QtGui.QTextEdit(self.page_3)
        self.startgcode.setGeometry(QtCore.QRect(0, 0, 431, 761))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.startgcode.setFont(font)
        self.startgcode.setObjectName("startgcode")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.endgcode = QtGui.QTextEdit(self.page_4)
        self.endgcode.setGeometry(QtCore.QRect(0, 0, 431, 761))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.endgcode.setFont(font)
        self.endgcode.setObjectName("endgcode")
        self.stackedWidget_2.addWidget(self.page_4)
        self.tabWidget.addTab(self.start_end_gcode, "")
        self.slice_modes.addWidget(self.normal)
        self.simple = QtGui.QWidget()
        self.simple.setObjectName("simple")
        self.layoutWidget9 = QtGui.QWidget(self.simple)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 10, 201, 361))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.quickprint_profile = QtGui.QGroupBox(self.layoutWidget9)
        self.quickprint_profile.setMaximumSize(QtCore.QSize(16777215, 120))
        self.quickprint_profile.setAutoFillBackground(False)
        self.quickprint_profile.setStyleSheet("")
        self.quickprint_profile.setFlat(False)
        self.quickprint_profile.setCheckable(False)
        self.quickprint_profile.setObjectName("quickprint_profile")
        self.layoutWidget10 = QtGui.QWidget(self.quickprint_profile)
        self.layoutWidget10.setGeometry(QtCore.QRect(4, 20, 171, 77))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.high_quality = QtGui.QRadioButton(self.layoutWidget10)
        self.high_quality.setObjectName("high_quality")
        self.verticalLayout.addWidget(self.high_quality)
        self.normal_quality = QtGui.QRadioButton(self.layoutWidget10)
        self.normal_quality.setChecked(True)
        self.normal_quality.setObjectName("normal_quality")
        self.verticalLayout.addWidget(self.normal_quality)
        self.fast_low_quality = QtGui.QRadioButton(self.layoutWidget10)
        self.fast_low_quality.setObjectName("fast_low_quality")
        self.verticalLayout.addWidget(self.fast_low_quality)
        self.verticalLayout_3.addWidget(self.quickprint_profile)
        self.material = QtGui.QGroupBox(self.layoutWidget9)
        self.material.setMaximumSize(QtCore.QSize(16777215, 150))
        self.material.setObjectName("material")
        self.layoutWidget11 = QtGui.QWidget(self.material)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 20, 131, 104))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pla = QtGui.QRadioButton(self.layoutWidget11)
        self.pla.setChecked(True)
        self.pla.setObjectName("pla")
        self.verticalLayout_2.addWidget(self.pla)
        self.abs = QtGui.QRadioButton(self.layoutWidget11)
        self.abs.setObjectName("abs")
        self.verticalLayout_2.addWidget(self.abs)
        self.label = QtGui.QLabel(self.layoutWidget11)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.simple_filament_diameter = QtGui.QLineEdit(self.layoutWidget11)
        self.simple_filament_diameter.setInputMask("")
        self.simple_filament_diameter.setObjectName("simple_filament_diameter")
        self.verticalLayout_2.addWidget(self.simple_filament_diameter)
        self.verticalLayout_3.addWidget(self.material)
        self.other = QtGui.QGroupBox(self.layoutWidget9)
        self.other.setMaximumSize(QtCore.QSize(16777215, 80))
        self.other.setObjectName("other")
        self.print_support_structure = QtGui.QCheckBox(self.other)
        self.print_support_structure.setGeometry(QtCore.QRect(0, 20, 181, 21))
        self.print_support_structure.setObjectName("print_support_structure")
        self.verticalLayout_3.addWidget(self.other)
        self.slice_modes.addWidget(self.simple)
        self.horizontalLayout_3.addWidget(self.left_widget)
        self.right_widget = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_widget.sizePolicy().hasHeightForWidth())
        self.right_widget.setSizePolicy(sizePolicy)
        self.right_widget.setObjectName("right_widget")
        self.horizontalLayout_3.addWidget(self.right_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        self.menuMachine = QtGui.QMenu(self.menubar)
        self.menuMachine.setObjectName("menuMachine")
        self.menuExpert = QtGui.QMenu(self.menubar)
        self.menuExpert.setTearOffEnabled(False)
        self.menuExpert.setObjectName("menuExpert")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_model_file_tCTRL_L = QtGui.QAction(MainWindow)
        self.actionLoad_model_file_tCTRL_L.setObjectName("actionLoad_model_file_tCTRL_L")
        self.actionSave_model = QtGui.QAction(MainWindow)
        self.actionSave_model.setObjectName("actionSave_model")
        self.actionReload_platform = QtGui.QAction(MainWindow)
        self.actionReload_platform.setObjectName("actionReload_platform")
        self.actionReload_platform_2 = QtGui.QAction(MainWindow)
        self.actionReload_platform_2.setObjectName("actionReload_platform_2")
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionSave_GCode = QtGui.QAction(MainWindow)
        self.actionSave_GCode.setObjectName("actionSave_GCode")
        self.actionShow_slice_engine_log = QtGui.QAction(MainWindow)
        self.actionShow_slice_engine_log.setObjectName("actionShow_slice_engine_log")
        self.actionOpen_Profile = QtGui.QAction(MainWindow)
        self.actionOpen_Profile.setObjectName("actionOpen_Profile")
        self.actionSave_Profile = QtGui.QAction(MainWindow)
        self.actionSave_Profile.setObjectName("actionSave_Profile")
        self.actionLoad_Profile_from_GCode = QtGui.QAction(MainWindow)
        self.actionLoad_Profile_from_GCode.setObjectName("actionLoad_Profile_from_GCode")
        self.actionReset_Profile_to_default = QtGui.QAction(MainWindow)
        self.actionReset_Profile_to_default.setObjectName("actionReset_Profile_to_default")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMachine_settings = QtGui.QAction(MainWindow)
        self.actionMachine_settings.setObjectName("actionMachine_settings")
        self.actionRecent_Model_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Model_Files.setObjectName("actionRecent_Model_Files")
        self.actionRecent_Profile_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Profile_Files.setObjectName("actionRecent_Profile_Files")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPID_Debugger = QtGui.QAction(MainWindow)
        self.actionPID_Debugger.setObjectName("actionPID_Debugger")
        self.actionCopy_profile_to_clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_profile_to_clipboard.setObjectName("actionCopy_profile_to_clipboard")
        self.actionPrint_all_at_once = QtGui.QAction(MainWindow)
        self.actionPrint_all_at_once.setObjectName("actionPrint_all_at_once")
        self.actionPrint_one_at_a_time = QtGui.QAction(MainWindow)
        self.actionPrint_one_at_a_time.setObjectName("actionPrint_one_at_a_time")
        self.actionMachine_settings_2 = QtGui.QAction(MainWindow)
        self.actionMachine_settings_2.setObjectName("actionMachine_settings_2")
        self.actionInstall_custom_firmware = QtGui.QAction(MainWindow)
        self.actionInstall_custom_firmware.setObjectName("actionInstall_custom_firmware")
        self.actionSwitch_to_quickprint = QtGui.QAction(MainWindow)
        self.actionSwitch_to_quickprint.setCheckable(True)
        self.actionSwitch_to_quickprint.setChecked(True)
        self.actionSwitch_to_quickprint.setObjectName("actionSwitch_to_quickprint")
        self.actionSwitch_to_expert_mode = QtGui.QAction(MainWindow)
        self.actionSwitch_to_expert_mode.setCheckable(True)
        self.actionSwitch_to_expert_mode.setObjectName("actionSwitch_to_expert_mode")
        self.actionOpen_expert_settings = QtGui.QAction(MainWindow)
        self.actionOpen_expert_settings.setObjectName("actionOpen_expert_settings")
        self.actionRun_first_run_wizard = QtGui.QAction(MainWindow)
        self.actionRun_first_run_wizard.setObjectName("actionRun_first_run_wizard")
        self.actionRun_bed_leveling_wizard = QtGui.QAction(MainWindow)
        self.actionRun_bed_leveling_wizard.setObjectName("actionRun_bed_leveling_wizard")
        self.actionRun_head_offset_wizard = QtGui.QAction(MainWindow)
        self.actionRun_head_offset_wizard.setObjectName("actionRun_head_offset_wizard")
        self.actionOnline_documentation = QtGui.QAction(MainWindow)
        self.actionOnline_documentation.setObjectName("actionOnline_documentation")
        self.actionReport_a_problem = QtGui.QAction(MainWindow)
        self.actionReport_a_problem.setObjectName("actionReport_a_problem")
        self.actionCheck_for_update = QtGui.QAction(MainWindow)
        self.actionCheck_for_update.setObjectName("actionCheck_for_update")
        self.menu_File.addAction(self.actionLoad_model_file_tCTRL_L)
        self.menu_File.addAction(self.actionSave_model)
        self.menu_File.addAction(self.actionReload_platform)
        self.menu_File.addAction(self.actionReload_platform_2)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPrint)
        self.menu_File.addAction(self.actionSave_GCode)
        self.menu_File.addAction(self.actionShow_slice_engine_log)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen_Profile)
        self.menu_File.addAction(self.actionSave_Profile)
        self.menu_File.addAction(self.actionLoad_Profile_from_GCode)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionReset_Profile_to_default)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPreferences)
        self.menu_File.addAction(self.actionMachine_settings)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionRecent_Model_Files)
        self.menu_File.addAction(self.actionRecent_Profile_Files)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Tools.addAction(self.actionPID_Debugger)
        self.menu_Tools.addAction(self.actionCopy_profile_to_clipboard)
        self.menu_Tools.addSeparator()
        self.menu_Tools.addAction(self.actionPrint_all_at_once)
        self.menu_Tools.addAction(self.actionPrint_one_at_a_time)
        self.menuMachine.addAction(self.actionMachine_settings_2)
        self.menuMachine.addSeparator()
        self.menuMachine.addAction(self.actionInstall_custom_firmware)
        self.menuExpert.addAction(self.actionSwitch_to_quickprint)
        self.menuExpert.addAction(self.actionSwitch_to_expert_mode)
        self.menuExpert.addSeparator()
        self.menuExpert.addAction(self.actionOpen_expert_settings)
        self.menuExpert.addSeparator()
        self.menuExpert.addAction(self.actionRun_first_run_wizard)
        self.menuExpert.addAction(self.actionRun_bed_leveling_wizard)
        self.menuExpert.addAction(self.actionRun_head_offset_wizard)
        self.menuHelp.addAction(self.actionOnline_documentation)
        self.menuHelp.addAction(self.actionReport_a_problem)
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuMachine.menuAction())
        self.menubar.addAction(self.menuExpert.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.slice_modes.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Omni 3D App", None, QtGui.QApplication.UnicodeUTF8))
        self.basic.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.layer_height_label.setText(QtGui.QApplication.translate("MainWindow", "Layer height (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.wall_thickness_label.setText(QtGui.QApplication.translate("MainWindow", "Shell thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.retraction_enable.setText(QtGui.QApplication.translate("MainWindow", "Enable retraction", None, QtGui.QApplication.UnicodeUTF8))
        self.fill_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.solid_layer_thickness_label.setText(QtGui.QApplication.translate("MainWindow", "Bottom/Top thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.fill_density_label.setText(QtGui.QApplication.translate("MainWindow", "Fill density (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_temperature_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Speed and Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.print_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Print speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_temperature_label.setText(QtGui.QApplication.translate("MainWindow", "Printing temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_temperature2_label.setText(QtGui.QApplication.translate("MainWindow", "2nd nozzle temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_temperature3_label.setText(QtGui.QApplication.translate("MainWindow", "3th nozzle temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_temperature4_label.setText(QtGui.QApplication.translate("MainWindow", "4th nozzle temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_bed_temperature_label.setText(QtGui.QApplication.translate("MainWindow", "Bed temperature (C)", None, QtGui.QApplication.UnicodeUTF8))
        self.support_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Support", None, QtGui.QApplication.UnicodeUTF8))
        self.support_label.setText(QtGui.QApplication.translate("MainWindow", "Support type", None, QtGui.QApplication.UnicodeUTF8))
        self.platform_adhesion_label.setText(QtGui.QApplication.translate("MainWindow", "Platform adhesion type", None, QtGui.QApplication.UnicodeUTF8))
        self.support_dual_extrusion_label.setText(QtGui.QApplication.translate("MainWindow", "Support dual extrusion", None, QtGui.QApplication.UnicodeUTF8))
        self.dual_extursion_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Dual extrusion", None, QtGui.QApplication.UnicodeUTF8))
        self.wipe_tower.setText(QtGui.QApplication.translate("MainWindow", "Wipe&prime tower", None, QtGui.QApplication.UnicodeUTF8))
        self.ooze_shield.setText(QtGui.QApplication.translate("MainWindow", "Ooze shield", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Filament", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_diameter_label.setText(QtGui.QApplication.translate("MainWindow", "Diameter (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_diameter2_label.setText(QtGui.QApplication.translate("MainWindow", "Diameter2 (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_diameter3_label.setText(QtGui.QApplication.translate("MainWindow", "Diameter3 (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_diameter4_label.setText(QtGui.QApplication.translate("MainWindow", "Diameter4 (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.filament_flow_label.setText(QtGui.QApplication.translate("MainWindow", "Flow (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic), QtGui.QApplication.translate("MainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.machine_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.nozzle_size_label.setText(QtGui.QApplication.translate("MainWindow", "Nozzle size (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.retraction_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Retraction", None, QtGui.QApplication.UnicodeUTF8))
        self.retraction_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.retraction_amount_label.setText(QtGui.QApplication.translate("MainWindow", "Distance (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.retraction_dual_amount_label.setText(QtGui.QApplication.translate("MainWindow", "Dual extrusion switch amount (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_groupbox_advanced.setTitle(QtGui.QApplication.translate("MainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.bottom_thickness_label.setText(QtGui.QApplication.translate("MainWindow", "Initial layer thickness (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.layer0_width_factor_label.setText(QtGui.QApplication.translate("MainWindow", "Initial layer line width (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.object_sink_label.setText(QtGui.QApplication.translate("MainWindow", "Cut off object bottom (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.overlap_dual_label.setText(QtGui.QApplication.translate("MainWindow", "Dual extursion overlap (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.speed_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.travel_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Travel speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.bottom_layer_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Bottom layer speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.infill_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Infill speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.inset0_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Outer shell speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.insetx_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Inner shell speed (mm/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.cool_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Cool", None, QtGui.QApplication.UnicodeUTF8))
        self.cool_min_layer_time_label.setText(QtGui.QApplication.translate("MainWindow", "Minimal layer time (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.fan_enabled.setText(QtGui.QApplication.translate("MainWindow", "Enable cooling fan", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced), QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.plugins_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Plugins:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.plugin_config.isSortingEnabled()
        self.plugin_config.setSortingEnabled(False)
        self.plugin_config.item(0).setText(QtGui.QApplication.translate("MainWindow", "Tweak At Z 3.1.2", None, QtGui.QApplication.UnicodeUTF8))
        self.plugin_config.item(1).setText(QtGui.QApplication.translate("MainWindow", "Pause at height", None, QtGui.QApplication.UnicodeUTF8))
        self.plugin_config.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Choose", None, QtGui.QApplication.UnicodeUTF8))
        self.enabled_plugins_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Enabled plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plugins), QtGui.QApplication.translate("MainWindow", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        self.listWidget_2.item(0).setText(QtGui.QApplication.translate("MainWindow", "start.gcode", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.item(1).setText(QtGui.QApplication.translate("MainWindow", "end.gcode", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.start_end_gcode), QtGui.QApplication.translate("MainWindow", "Start/End-GCode", None, QtGui.QApplication.UnicodeUTF8))
        self.quickprint_profile.setTitle(QtGui.QApplication.translate("MainWindow", "Select a quickprint profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.high_quality.setText(QtGui.QApplication.translate("MainWindow", "High quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.normal_quality.setText(QtGui.QApplication.translate("MainWindow", "Normal quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.fast_low_quality.setText(QtGui.QApplication.translate("MainWindow", "Fast low quality print", None, QtGui.QApplication.UnicodeUTF8))
        self.material.setTitle(QtGui.QApplication.translate("MainWindow", "Material", None, QtGui.QApplication.UnicodeUTF8))
        self.pla.setText(QtGui.QApplication.translate("MainWindow", "PLA", None, QtGui.QApplication.UnicodeUTF8))
        self.abs.setText(QtGui.QApplication.translate("MainWindow", "ABS", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Diameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.other.setTitle(QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.print_support_structure.setText(QtGui.QApplication.translate("MainWindow", "Print support structure", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Tools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMachine.setTitle(QtGui.QApplication.translate("MainWindow", "Machine", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExpert.setTitle(QtGui.QApplication.translate("MainWindow", "Expert", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_model_file_tCTRL_L.setText(QtGui.QApplication.translate("MainWindow", "Load model file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_model.setText(QtGui.QApplication.translate("MainWindow", "Save model...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_platform.setText(QtGui.QApplication.translate("MainWindow", "Reload platform", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_platform_2.setText(QtGui.QApplication.translate("MainWindow", "Clear platform", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_GCode.setText(QtGui.QApplication.translate("MainWindow", "Save GCode...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_slice_engine_log.setText(QtGui.QApplication.translate("MainWindow", "Show slice engine log...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Profile.setText(QtGui.QApplication.translate("MainWindow", "Open Profile...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Profile.setText(QtGui.QApplication.translate("MainWindow", "Save Profile...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Profile_from_GCode.setText(QtGui.QApplication.translate("MainWindow", "Load Profile from GCode...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Profile_to_default.setText(QtGui.QApplication.translate("MainWindow", "Reset Profile to default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMachine_settings.setText(QtGui.QApplication.translate("MainWindow", "Machine settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Model_Files.setText(QtGui.QApplication.translate("MainWindow", "Recent Model Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecent_Profile_Files.setText(QtGui.QApplication.translate("MainWindow", "Recent Profile Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPID_Debugger.setText(QtGui.QApplication.translate("MainWindow", "PID Debugger...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_profile_to_clipboard.setText(QtGui.QApplication.translate("MainWindow", "Copy profile to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_all_at_once.setText(QtGui.QApplication.translate("MainWindow", "Print all at once", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint_one_at_a_time.setText(QtGui.QApplication.translate("MainWindow", "Print one at a time", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMachine_settings_2.setText(QtGui.QApplication.translate("MainWindow", "Machine settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInstall_custom_firmware.setText(QtGui.QApplication.translate("MainWindow", "Install custom firmware...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_to_quickprint.setText(QtGui.QApplication.translate("MainWindow", "Switch to quickprint...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch_to_expert_mode.setText(QtGui.QApplication.translate("MainWindow", "Switch to full settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_expert_settings.setText(QtGui.QApplication.translate("MainWindow", "Open expert settings...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_first_run_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run first run wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_bed_leveling_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run bed leveling wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_head_offset_wizard.setText(QtGui.QApplication.translate("MainWindow", "Run head offset wizard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOnline_documentation.setText(QtGui.QApplication.translate("MainWindow", "Online documentation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_a_problem.setText(QtGui.QApplication.translate("MainWindow", "Report a problem...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheck_for_update.setText(QtGui.QApplication.translate("MainWindow", "Check for update...", None, QtGui.QApplication.UnicodeUTF8))

